[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "dynamic-programming-rl"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["."]
include = ["algorithms*", "utils*"]
